### ISSUE TITLE
Changes to state workflow

### ISSUE THREAD

**Issue by raboof** [apache/security-vulnogram#61]
## Current process:

```mermaid
graph TD;
    RESERVED-- pmc --->DRAFT;
    DRAFT-- pmc --->REVIEW;
    REVIEW-- security --->DRAFT;
    DRAFT-- pmc --->READY;
    READY-- security --->PUBLIC;
```

The PMC clicks the "Send these Emails" button in the READY state and populates a `vendor-advisory` Reference

## Desired process:

```mermaid
graph TD;
    RESERVED-- pmc --->DRAFT;
    DRAFT-- pmc --->READY;
    DRAFT-- pmc --->SECURITY-REVIEW;
    SECURITY-REVIEW-- security --->DRAFT;
    DRAFT-- pmc --->PMC-REVIEW;
    PMC-REVIEW-- pmc --->READY
    READY-- security --->PUBLIC;
```

Desired changes in behavior to get there:
* [ ] Split REVIEW into SECURITY-REVIEW and PMC-REVIEW #57
* [ ] Automatically send emails and set `vendor-advisory` when the CVE is moved to READY/PUBLIC #42
* [ ] Make the CVE readonly for the pmc when in the READY state #41 
* [ ] Automatically move from READY to PUBLIC when the CVE has previously been reviewed
* [ ] Automatically post the CVE to Mitre when the CVE is moved to PUBLIC
* [ ] Only allow moving to READY/PUBLIC when all validations succeed

**Comment by iamamoose** [comment]
The outcome of PMC-REVIEW could be back to DRAFT (by PMC)

Is READY sufficent to allow a PMC to put issues into a state where it's ready to go public but not public yet.  Should we have the PMC have a READY stage (ready to go public, not public yet), a PUBLIC stage (we've made it public by making the emails live, update live etc) and then a PUBLISHED (we've pushed it to CVE.org) state?

**Comment by raboof** [comment]
> Another outcome of PMC-REVIEW could also be back to DRAFT (by PMC)

Makes sense, updated

> a state where it's ready to go public but not public yet

This would be for situations where they're waiting for the release to be published, or when they want some delay between releasing and disclosing? That makes sense to me, updating. I guess they also can go straight from DRAFT or PMC-REVIEW to PUBLIC for smaller projects.

> Should we have the PMC have a READY stage (ready to go public, not public yet), a PUBLIC stage (we've made it public by making the emails live, update live etc) and then a PUBLISHED (we've pushed it to CVE.org) state?

Right, so the pmc would make the transition between `READY` and `PUBLIC`, and then we'd review it (if still needed) and trigger the push to Mitre. I'm not *sure* that needs an additional `PUBLISHED` state, but it might be nice, updating.

Btw, why do we require a Security review for publishing the CVE, but after sending the emails? Is that just 'how it grew' or do we have a reason to want it like that? It might make more sense to send emails and publish the CVE after the review by us and the move to `PUBLIC`?
